const data={
    products:[
        {
            name:"Nike Slim Shirt",
            slug:"Nike-Slim-Shirt",
            category:"Shirts",
            image:"/images/p1.jpg",
            price:120,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            description:"high quality product",
        },
        {
            name:"adidas Slim Shirt",
            slug:"adidas-Slim-Shirt",
            category:"Shirts",
            image:"/images/p2.jpg",
            price:120,
            brand:"adidas",
            rating:4.5,
            numReviews:10,
            description:"high quality product",
        },
        {
            name:"Nike pant",
            slug:"Nike-pant",
            category:"pant",
            image:"/images/p3.jpg",
            price:120,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            description:"high quality product",
        },
        {
            name:"adidas pant",
            slug:"adidas-pant",
            category:"pant",
            image:"/images/p4.jpg",
            price:120,
            brand:"adidas",
            rating:4.5,
            numReviews:10,
            description:"high quality product",
        },  
    ],
};

export default data;